-- +goose Up
ALTER TABLE apps ADD COLUMN memory TEXT NOT NULL DEFAULT '256Mi';
ALTER TABLE apps ADD COLUMN cpu TEXT NOT NULL DEFAULT '0.5';

-- +goose Down
ALTER TABLE apps DROP COLUMN memory;
ALTER TABLE apps DROP COLUMN cpu;
