// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIKey struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type CreateAPIKeyResult struct {
	APIKey *APIKey `json:"apiKey"`
	Secret string  `json:"secret"`
}

type DeleteServiceResult struct {
	ServiceID string `json:"serviceId"`
	Name      string `json:"name"`
	Message   string `json:"message"`
}

type EnvVar struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type MetricDataPoint struct {
	Timestamp time.Time `json:"timestamp"`
	Value     float64   `json:"value"`
}

type MetricSeries struct {
	Metric     string             `json:"metric"`
	DataPoints []*MetricDataPoint `json:"dataPoints"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Project struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Ref       string     `json:"ref"`
	Services  []*Service `json:"services"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type ProjectConnection struct {
	Nodes      []*Project `json:"nodes"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int32      `json:"totalCount"`
}

type Query struct {
}

type Resource struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Type      string            `json:"type"`
	Provider  string            `json:"provider"`
	Region    string            `json:"region"`
	Status    string            `json:"status"`
	Metadata  *ResourceMetadata `json:"metadata,omitempty"`
	ProjectID *string           `json:"projectId,omitempty"`
	Project   *Project          `json:"project,omitempty"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

type ResourceConnection struct {
	Nodes      []*Resource `json:"nodes"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int32       `json:"totalCount"`
}

type ResourceMetadata struct {
	Size     *string `json:"size,omitempty"`
	Hostname *string `json:"hostname,omitempty"`
	Group    *string `json:"group,omitempty"`
}

type Service struct {
	ID                 string    `json:"id"`
	ProjectID          string    `json:"projectId"`
	Project            *Project  `json:"project,omitempty"`
	Name               *string   `json:"name,omitempty"`
	Repo               string    `json:"repo"`
	Branch             string    `json:"branch"`
	BuildStatus        string    `json:"buildStatus"`
	RuntimeStatus      *string   `json:"runtimeStatus,omitempty"`
	ErrorMessage       *string   `json:"errorMessage,omitempty"`
	EnvVars            []*EnvVar `json:"envVars"`
	Fqdn               *string   `json:"fqdn,omitempty"`
	Port               string    `json:"port"`
	GitProvider        string    `json:"gitProvider"`
	CommitHash         *string   `json:"commitHash,omitempty"`
	Memory             string    `json:"memory"`
	Vcpus              string    `json:"vcpus"`
	CustomDomain       *string   `json:"customDomain,omitempty"`
	CustomDomainStatus *string   `json:"customDomainStatus,omitempty"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
}

type ServiceConnection struct {
	Nodes      []*Service `json:"nodes"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int32      `json:"totalCount"`
}

type ServiceMetrics struct {
	CPUUsage                   *MetricSeries `json:"cpuUsage"`
	MemoryUsageMb              *MetricSeries `json:"memoryUsageMB"`
	NetworkReceiveBytesPerSec  *MetricSeries `json:"networkReceiveBytesPerSec"`
	NetworkTransmitBytesPerSec *MetricSeries `json:"networkTransmitBytesPerSec"`
	MemoryLimitMb              float64       `json:"memoryLimitMB"`
	CPULimitVCPUs              float64       `json:"cpuLimitVCPUs"`
}

type User struct {
	ID                      string    `json:"id"`
	Email                   *string   `json:"email,omitempty"`
	DisplayName             *string   `json:"displayName,omitempty"`
	GithubUsername          *string   `json:"githubUsername,omitempty"`
	AvatarURL               *string   `json:"avatarUrl,omitempty"`
	CreatedAt               time.Time `json:"createdAt"`
	GithubAppInstallationID *string   `json:"githubAppInstallationId,omitempty"`
	GithubScopes            []string  `json:"githubScopes"`
}

type MetricTimeRange string

const (
	MetricTimeRangeOneHour    MetricTimeRange = "ONE_HOUR"
	MetricTimeRangeSixHours   MetricTimeRange = "SIX_HOURS"
	MetricTimeRangeSevenDays  MetricTimeRange = "SEVEN_DAYS"
	MetricTimeRangeThirtyDays MetricTimeRange = "THIRTY_DAYS"
)

var AllMetricTimeRange = []MetricTimeRange{
	MetricTimeRangeOneHour,
	MetricTimeRangeSixHours,
	MetricTimeRangeSevenDays,
	MetricTimeRangeThirtyDays,
}

func (e MetricTimeRange) IsValid() bool {
	switch e {
	case MetricTimeRangeOneHour, MetricTimeRangeSixHours, MetricTimeRangeSevenDays, MetricTimeRangeThirtyDays:
		return true
	}
	return false
}

func (e MetricTimeRange) String() string {
	return string(e)
}

func (e *MetricTimeRange) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MetricTimeRange(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MetricTimeRange", str)
	}
	return nil
}

func (e MetricTimeRange) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MetricTimeRange) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MetricTimeRange) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
