// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIKey struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type App struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"projectId"`
	Name          *string   `json:"name,omitempty"`
	Repo          string    `json:"repo"`
	Branch        string    `json:"branch"`
	BuildStatus   string    `json:"buildStatus"`
	RuntimeStatus *string   `json:"runtimeStatus,omitempty"`
	ErrorMessage  *string   `json:"errorMessage,omitempty"`
	EnvVars       []*EnvVar `json:"envVars"`
	Fqdn          *string   `json:"fqdn,omitempty"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type AppConnection struct {
	Nodes      []*App    `json:"nodes"`
	PageInfo   *PageInfo `json:"pageInfo"`
	TotalCount int32     `json:"totalCount"`
}

type CreateAPIKeyResult struct {
	APIKey *APIKey `json:"apiKey"`
	Secret string  `json:"secret"`
}

type DeleteAppResult struct {
	AppID   string `json:"appId"`
	Name    string `json:"name"`
	Message string `json:"message"`
}

type EnvVar struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Project struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Ref       string    `json:"ref"`
	Apps      []*App    `json:"apps"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ProjectConnection struct {
	Nodes      []*Project `json:"nodes"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int32      `json:"totalCount"`
}

type Query struct {
}

type User struct {
	ID                      string    `json:"id"`
	GithubUsername          string    `json:"githubUsername"`
	AvatarURL               *string   `json:"avatarUrl,omitempty"`
	CreatedAt               time.Time `json:"createdAt"`
	GithubAppInstallationID *string   `json:"githubAppInstallationId,omitempty"`
	GithubScopes            []string  `json:"githubScopes"`
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
