// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type APIKey struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type CreateAPIKeyResult struct {
	APIKey *APIKey `json:"apiKey"`
	Secret string  `json:"secret"`
}

type DeployInput struct {
	Repo           string         `json:"repo"`
	Branch         string         `json:"branch"`
	ServerUUID     string         `json:"serverUuid"`
	Name           *string        `json:"name,omitempty"`
	BuildPack      *BuildPack     `json:"buildPack,omitempty"`
	Port           *int32         `json:"port,omitempty"`
	EnvVars        []*EnvVarInput `json:"envVars,omitempty"`
	Memory         *string        `json:"memory,omitempty"`
	CPU            *string        `json:"cpu,omitempty"`
	InstallCommand *string        `json:"installCommand,omitempty"`
	BuildCommand   *string        `json:"buildCommand,omitempty"`
	StartCommand   *string        `json:"startCommand,omitempty"`
	InstantDeploy  *bool          `json:"instantDeploy,omitempty"`
}

type DeployResult struct {
	Deployment     *Deployment `json:"deployment"`
	DeploymentUUID *string     `json:"deploymentUuid,omitempty"`
	Message        string      `json:"message"`
}

type Deployment struct {
	UUID      string  `json:"uuid"`
	Name      string  `json:"name"`
	Repo      string  `json:"repo"`
	Branch    string  `json:"branch"`
	Status    string  `json:"status"`
	Fqdn      *string `json:"fqdn,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

type EnvVarInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID                      string    `json:"id"`
	GithubUsername          string    `json:"githubUsername"`
	AvatarURL               *string   `json:"avatarUrl,omitempty"`
	CreatedAt               time.Time `json:"createdAt"`
	GithubAppInstallationID *string   `json:"githubAppInstallationId,omitempty"`
	GithubScopes            []string  `json:"githubScopes"`
}

type BuildPack string

const (
	BuildPackNixpacks      BuildPack = "NIXPACKS"
	BuildPackDockerfile    BuildPack = "DOCKERFILE"
	BuildPackStatic        BuildPack = "STATIC"
	BuildPackDockerCompose BuildPack = "DOCKER_COMPOSE"
)

var AllBuildPack = []BuildPack{
	BuildPackNixpacks,
	BuildPackDockerfile,
	BuildPackStatic,
	BuildPackDockerCompose,
}

func (e BuildPack) IsValid() bool {
	switch e {
	case BuildPackNixpacks, BuildPackDockerfile, BuildPackStatic, BuildPackDockerCompose:
		return true
	}
	return false
}

func (e BuildPack) String() string {
	return string(e)
}

func (e *BuildPack) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BuildPack(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BuildPack", str)
	}
	return nil
}

func (e BuildPack) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BuildPack) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BuildPack) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Role string

const (
	RoleAdmin Role = "ADMIN"
	RoleUser  Role = "USER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleUser,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleUser:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
