// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type APIKey struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type CreateAPIKeyResult struct {
	APIKey *APIKey `json:"apiKey"`
	Secret string  `json:"secret"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID                  string    `json:"id"`
	GithubUsername      string    `json:"githubUsername"`
	AvatarURL           *string   `json:"avatarUrl,omitempty"`
	CreatedAt           time.Time `json:"createdAt"`
	HasFlyioCredentials bool      `json:"hasFlyioCredentials"`
}
