all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

    # Core cluster settings
    cluster_name: deploy-mcp
    k3s_version: "v1.31.4+k3s1"
    apps_domain: ml.ink

    # Dedicated server route target for Hetzner cloud network
    vswitch_network_cidr: 10.0.0.0/16
    private_gateway: 10.0.1.1
    vswitch_vlan_id: 4000

    # Registry mapping for kubelet pulls
    registry_ip: 10.0.1.5
    registry_host_alias: registry.internal
    registry_port: 5000
    # K3s API endpoint for agent join
    k3s_server_endpoint_ip: 10.0.0.3
    registry_allowed_cidrs:
      - 10.0.1.0/24
      - 10.0.0.0/16
    metrics_allowed_cidrs:
      - 10.0.1.0/24
      - 10.0.0.0/16

    # TLS / cert-manager defaults
    cert_manager_email: ops@ml.ink
    cloudflare_zone: ml.ink

    # Temporal worker non-secret settings
    github_app_id: "2782695"
    temporal_address: "us-central1.gcp.api.temporal.io:7233"
    temporal_namespace: "mlink.svtnk"

    # Optional secret values (leave blank and provide via extra-vars or vault)
    cloudflare_api_token: ""
    loki_basic_auth_users: ""
    prometheus_basic_auth_users: ""
    powerdns_db_password: ""
    powerdns_api_key: ""
    powerdns_tsig_key: ""
    instatus_api_key: ""
    instatus_page_id: ""

  children:
    ctrl:
      vars:
        node_pool_name: ctrl
        node_taint: ""
      hosts:
        ctrl-1:
          ansible_host: 46.224.206.46
          private_ip: 10.0.0.3
          private_iface: enp7s0
          is_dedicated: false

    ops:
      vars:
        node_pool_name: ops
        node_taint: pool=ops:NoSchedule
      hosts:
        ops-1:
          ansible_host: 176.9.150.48
          private_ip: 10.0.1.4
          private_iface: vlan4000
          is_dedicated: true
          physical_nic: enp41s0

    build:
      vars:
        node_pool_name: build
        node_taint: pool=build:NoSchedule
      hosts:
        build-1:
          ansible_host: 78.46.80.236
          private_ip: 10.0.1.5
          private_iface: vlan4000
          is_dedicated: true
          physical_nic: enp6s0

    run:
      vars:
        node_pool_name: run
        node_taint: ""
        k3s_agent_kubelet_args:
          - "max-pods=800"
          - "pods-per-core=0"
          - "kube-api-qps=100"
          - "kube-api-burst=200"
          - "serialize-image-pulls=false"
          - "node-status-update-frequency=30s"
      hosts:
        run-1:
          ansible_host: 148.251.156.12
          private_ip: 10.0.1.3
          private_iface: vlan4000
          is_dedicated: true
          physical_nic: enp195s0

    dns:
      hosts:
        powerdns-1:
          ansible_host: 46.225.84.41
          private_ip: 10.0.0.4
          private_iface: enp7s0
          is_dedicated: false

    dedicated:
      children:
        ops:
        build:
        run:
