package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/augustdev/autoclip/internal/authz"
	"github.com/augustdev/autoclip/internal/dns"
	"github.com/augustdev/autoclip/internal/graph/model"
)

// DelegateZone is the resolver for the delegateZone field.
func (r *mutationResolver) DelegateZone(ctx context.Context, zone string) (*model.DelegateZoneResult, error) {
	userID := authz.For(ctx).GetUserID()

	result, err := r.DNSService.DelegateZone(ctx, dns.DelegateZoneParams{
		UserID: userID,
		Zone:   zone,
	})
	if err != nil {
		return nil, err
	}

	return &model.DelegateZoneResult{
		ZoneID:       result.ZoneID,
		Zone:         result.Zone,
		Status:       result.Status,
		Instructions: result.Instructions,
	}, nil
}

// VerifyDelegation is the resolver for the verifyDelegation field.
func (r *mutationResolver) VerifyDelegation(ctx context.Context, zone string) (*model.VerifyDelegationResult, error) {
	userID := authz.For(ctx).GetUserID()

	result, err := r.DNSService.VerifyDelegation(ctx, dns.VerifyDelegationParams{
		UserID: userID,
		Zone:   zone,
	})
	if err != nil {
		return nil, err
	}

	var instructions *string
	if result.Instructions != "" {
		instructions = &result.Instructions
	}

	return &model.VerifyDelegationResult{
		ZoneID:       result.ZoneID,
		Zone:         result.Zone,
		Status:       result.Status,
		Message:      result.Message,
		Instructions: instructions,
	}, nil
}

// RemoveDelegation is the resolver for the removeDelegation field.
func (r *mutationResolver) RemoveDelegation(ctx context.Context, zone string) (*model.RemoveDelegationResult, error) {
	userID := authz.For(ctx).GetUserID()

	result, err := r.DNSService.RemoveDelegation(ctx, dns.RemoveDelegationParams{
		UserID: userID,
		Zone:   zone,
	})
	if err != nil {
		return nil, err
	}

	return &model.RemoveDelegationResult{
		ZoneID:  result.ZoneID,
		Message: result.Message,
	}, nil
}

// ListDelegatedZones is the resolver for the listDelegatedZones field.
func (r *queryResolver) ListDelegatedZones(ctx context.Context) ([]*model.DelegatedZone, error) {
	userID := authz.For(ctx).GetUserID()

	zones, err := r.DNSService.ListDelegations(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to list delegated zones: %w", err)
	}

	result := make([]*model.DelegatedZone, len(zones))
	for i, z := range zones {
		var errStr *string
		if z.LastError != nil {
			errStr = z.LastError
		}
		result[i] = &model.DelegatedZone{
			ID:        z.ID,
			Zone:      z.Zone,
			Status:    z.Status,
			Error:     errStr,
			CreatedAt: z.CreatedAt.Time,
		}
	}

	return result, nil
}
