package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/augustdev/autoclip/internal/authz"
	"github.com/augustdev/autoclip/internal/graph/model"
	"github.com/augustdev/autoclip/internal/k8sdeployments"
)

// ServiceMetrics is the resolver for the serviceMetrics field.
func (r *queryResolver) ServiceMetrics(ctx context.Context, serviceID string, timeRange model.MetricTimeRange) (*model.ServiceMetrics, error) {
	userID := authz.For(ctx).GetUserID()

	dbService, err := r.ServiceQueries.GetServiceByID(ctx, serviceID)
	if err != nil {
		return nil, fmt.Errorf("service not found")
	}
	if dbService.UserID != userID {
		return nil, fmt.Errorf("service not found")
	}

	user, err := r.AuthService.GetUserByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user")
	}

	username := k8sdeployments.ResolveUsername(*user)
	if username == "" {
		return nil, fmt.Errorf("user has no username configured")
	}

	project, err := r.ProjectQueries.GetProjectByID(ctx, dbService.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("failed to get project")
	}

	namespace := k8sdeployments.NamespaceName(username, project.Ref)

	svcName := ""
	if dbService.Name != nil {
		svcName = *dbService.Name
	}
	serviceName := k8sdeployments.ServiceName(svcName)

	start, end, step, err := resolveTimeRange(timeRange)
	if err != nil {
		return nil, err
	}

	metrics, err := r.PrometheusClient.GetServiceMetrics(ctx, namespace, serviceName, start, end, step)
	if err != nil {
		return nil, fmt.Errorf("metrics temporarily unavailable")
	}

	memoryLimitMB := parseMemoryToMB(dbService.Memory)
	cpuLimitVCPUs := parseCPUToVCPUs(dbService.Cpu)

	return &model.ServiceMetrics{
		CPUUsage:                   toModelSeries(metrics.CPUUsage),
		MemoryUsageMb:              toModelSeries(metrics.MemoryUsageMB),
		NetworkReceiveBytesPerSec:  toModelSeries(metrics.NetworkReceiveBytesPerSec),
		NetworkTransmitBytesPerSec: toModelSeries(metrics.NetworkTransmitBytesPerSec),
		MemoryLimitMb:              memoryLimitMB,
		CPULimitVCPUs:              cpuLimitVCPUs,
	}, nil
}
