package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/augustdev/autoclip/internal/authz"
	"github.com/augustdev/autoclip/internal/graph/model"
	"github.com/augustdev/autoclip/internal/storage/pg/generated/projects"
)

// ListProjects is the resolver for the listProjects field.
func (r *queryResolver) ListProjects(ctx context.Context, first *int32, after *string) (*model.ProjectConnection, error) {
	userID := authz.For(ctx).GetUserID()

	totalCount, err := r.ProjectQueries.CountProjectsByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to count projects: %w", err)
	}

	// For now, return all items
	limit := int32(1000)
	offset := int32(0)

	dbProjects, err := r.ProjectQueries.ListProjectsByUserID(ctx, projects.ListProjectsByUserIDParams{
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list projects: %w", err)
	}

	nodes := make([]*model.Project, len(dbProjects))
	for i, dbProject := range dbProjects {
		projectApps, err := r.getAppsForProject(ctx, dbProject.ID)
		if err != nil {
			return nil, fmt.Errorf("failed to get apps for project: %w", err)
		}
		nodes[i] = dbProjectToModel(&dbProject, projectApps)
	}

	var startCursor, endCursor *string
	if len(nodes) > 0 {
		startCursor = &nodes[0].ID
		endCursor = &nodes[len(nodes)-1].ID
	}

	return &model.ProjectConnection{
		Nodes: nodes,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int32(totalCount),
	}, nil
}

// ProjectDetails is the resolver for the projectDetails field.
func (r *queryResolver) ProjectDetails(ctx context.Context, id string) (*model.Project, error) {
	userID := authz.For(ctx).GetUserID()

	dbProject, err := r.ProjectQueries.GetProjectByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get project: %w", err)
	}

	if dbProject.UserID != userID {
		return nil, fmt.Errorf("project not found")
	}

	projectApps, err := r.getAppsForProject(ctx, dbProject.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get apps for project: %w", err)
	}

	return dbProjectToModel(&dbProject, projectApps), nil
}
