package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/augustdev/autoclip/internal/authz"
	"github.com/augustdev/autoclip/internal/graph/model"
	"github.com/augustdev/autoclip/internal/storage/pg/generated/resources"
)

// ListResources is the resolver for the listResources field.
func (r *queryResolver) ListResources(ctx context.Context, first *int32, after *string) (*model.ResourceConnection, error) {
	userID := authz.For(ctx).GetUserID()

	totalCount, err := r.ResourceQueries.CountResourcesByUser(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to count resources: %w", err)
	}

	limit := int32(1000)
	offset := int32(0)

	dbResources, err := r.ResourceQueries.ListResourcesByUser(ctx, resources.ListResourcesByUserParams{
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list resources: %w", err)
	}

	nodes := make([]*model.Resource, len(dbResources))
	for i, dbResource := range dbResources {
		nodes[i] = dbResourceToModel(&dbResource)
	}

	var startCursor, endCursor *string
	if len(nodes) > 0 {
		startCursor = &nodes[0].ID
		endCursor = &nodes[len(nodes)-1].ID
	}

	return &model.ResourceConnection{
		Nodes: nodes,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int32(totalCount),
	}, nil
}

// ResourceDetails is the resolver for the resourceDetails field.
func (r *queryResolver) ResourceDetails(ctx context.Context, id string) (*model.Resource, error) {
	userID := authz.For(ctx).GetUserID()

	dbResource, err := r.ResourceQueries.GetResourceByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get resource: %w", err)
	}

	if dbResource.UserID != userID {
		return nil, fmt.Errorf("resource not found")
	}

	return dbResourceToModel(&dbResource), nil
}

// Project is the resolver for the project field.
func (r *resourceResolver) Project(ctx context.Context, obj *model.Resource) (*model.Project, error) {
	if obj.ProjectID == nil {
		return nil, nil
	}

	dbProject, err := r.ProjectQueries.GetProjectByID(ctx, *obj.ProjectID)
	if err != nil {
		return nil, nil
	}

	return dbProjectToModel(&dbProject), nil
}

// Resource returns ResourceResolver implementation.
func (r *Resolver) Resource() ResourceResolver { return &resourceResolver{r} }

type resourceResolver struct{ *Resolver }
