package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/augustdev/autoclip/internal/authz"
	"github.com/augustdev/autoclip/internal/deployments"
	"github.com/augustdev/autoclip/internal/graph/model"
	"github.com/augustdev/autoclip/internal/storage/pg/generated/services"
)

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, name string, project *string) (*model.DeleteServiceResult, error) {
	userID := authz.For(ctx).GetUserID()

	projectRef := "default"
	if project != nil && *project != "" {
		projectRef = *project
	}

	result, err := r.DeployService.DeleteService(ctx, deployments.DeleteServiceParams{
		Name:    name,
		Project: projectRef,
		UserID:  userID,
	})
	if err != nil {
		return nil, err
	}

	return &model.DeleteServiceResult{
		ServiceID: result.ServiceID,
		Name:      result.Name,
		Message:   "Service deletion initiated",
	}, nil
}

// ListServices is the resolver for the listServices field.
func (r *queryResolver) ListServices(ctx context.Context, first *int32, after *string) (*model.ServiceConnection, error) {
	userID := authz.For(ctx).GetUserID()

	totalCount, err := r.ServiceQueries.CountServicesByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to count services: %w", err)
	}

	// For now, return all items (ignore pagination params)
	limit := int32(1000)
	offset := int32(0)

	dbServices, err := r.ServiceQueries.ListServicesByUserID(ctx, services.ListServicesByUserIDParams{
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list services: %w", err)
	}

	nodes, err := enrichServices(ctx, dbServices)
	if err != nil {
		return nil, fmt.Errorf("failed to enrich services: %w", err)
	}

	var startCursor, endCursor *string
	if len(nodes) > 0 {
		startCursor = &nodes[0].ID
		endCursor = &nodes[len(nodes)-1].ID
	}

	return &model.ServiceConnection{
		Nodes: nodes,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int32(totalCount),
	}, nil
}

// ServiceDetails is the resolver for the serviceDetails field.
func (r *queryResolver) ServiceDetails(ctx context.Context, id string) (*model.Service, error) {
	userID := authz.For(ctx).GetUserID()

	dbSvc, err := r.ServiceQueries.GetServiceByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get service: %w", err)
	}

	if dbSvc.UserID != userID {
		return nil, fmt.Errorf("service not found")
	}

	svcs, err := enrichServices(ctx, []services.Service{dbSvc})
	if err != nil {
		return nil, fmt.Errorf("failed to enrich service: %w", err)
	}
	return svcs[0], nil
}

// Project is the resolver for the project field.
func (r *serviceResolver) Project(ctx context.Context, obj *model.Service) (*model.Project, error) {
	dbProject, err := r.ProjectQueries.GetProjectByID(ctx, obj.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch project %s: %w", obj.ProjectID, err)
	}

	return dbProjectToModel(&dbProject), nil
}

// Service returns ServiceResolver implementation.
func (r *Resolver) Service() ServiceResolver { return &serviceResolver{r} }

type serviceResolver struct{ *Resolver }
