package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/augustdev/autoclip/internal/authz"
	"github.com/augustdev/autoclip/internal/graph/model"
	"github.com/augustdev/autoclip/internal/storage/pg/generated/services"
)

// DeleteService is the resolver for the deleteService field.
func (r *mutationResolver) DeleteService(ctx context.Context, name string, project *string) (*model.DeleteServiceResult, error) {
	userID := authz.For(ctx).GetUserID()

	projectRef := "default"
	if project != nil && *project != "" {
		projectRef = *project
	}

	svc, err := r.ServiceQueries.GetServiceByNameAndUserProject(ctx, services.GetServiceByNameAndUserProjectParams{
		Name:   &name,
		UserID: userID,
		Ref:    projectRef,
	})
	if err != nil {
		return nil, fmt.Errorf("service not found: %s in project %s", name, projectRef)
	}

	_, err = r.ServiceQueries.SoftDeleteService(ctx, svc.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to delete service: %w", err)
	}

	svcName := ""
	if svc.Name != nil {
		svcName = *svc.Name
	}

	return &model.DeleteServiceResult{
		ServiceID: svc.ID,
		Name:      svcName,
		Message:   "Service deleted successfully",
	}, nil
}

// ListServices is the resolver for the listServices field.
func (r *queryResolver) ListServices(ctx context.Context, first *int32, after *string) (*model.ServiceConnection, error) {
	userID := authz.For(ctx).GetUserID()

	totalCount, err := r.ServiceQueries.CountServicesByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to count services: %w", err)
	}

	// For now, return all items (ignore pagination params)
	limit := int32(1000)
	offset := int32(0)

	dbServices, err := r.ServiceQueries.ListServicesByUserID(ctx, services.ListServicesByUserIDParams{
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list services: %w", err)
	}

	nodes := make([]*model.Service, len(dbServices))
	for i, dbSvc := range dbServices {
		nodes[i] = dbServiceToModel(&dbSvc)
		if cd, err := r.CustomDomainQueries.GetByServiceID(ctx, dbSvc.ID); err == nil {
			nodes[i].CustomDomain = &cd.Domain
			nodes[i].CustomDomainStatus = &cd.Status
		}
	}

	var startCursor, endCursor *string
	if len(nodes) > 0 {
		startCursor = &nodes[0].ID
		endCursor = &nodes[len(nodes)-1].ID
	}

	return &model.ServiceConnection{
		Nodes: nodes,
		PageInfo: &model.PageInfo{
			HasNextPage:     false,
			HasPreviousPage: false,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int32(totalCount),
	}, nil
}

// ServiceDetails is the resolver for the serviceDetails field.
func (r *queryResolver) ServiceDetails(ctx context.Context, id string) (*model.Service, error) {
	userID := authz.For(ctx).GetUserID()

	dbSvc, err := r.ServiceQueries.GetServiceByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get service: %w", err)
	}

	if dbSvc.UserID != userID {
		return nil, fmt.Errorf("service not found")
	}

	svcModel := dbServiceToModel(&dbSvc)
	if cd, err := r.CustomDomainQueries.GetByServiceID(ctx, dbSvc.ID); err == nil {
		svcModel.CustomDomain = &cd.Domain
		svcModel.CustomDomainStatus = &cd.Status
	}
	return svcModel, nil
}

// Project is the resolver for the project field.
func (r *serviceResolver) Project(ctx context.Context, obj *model.Service) (*model.Project, error) {
	dbProject, err := r.ProjectQueries.GetProjectByID(ctx, obj.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch project %s: %w", obj.ProjectID, err)
	}

	return dbProjectToModel(&dbProject, nil), nil
}

// Service returns ServiceResolver implementation.
func (r *Resolver) Service() ServiceResolver { return &serviceResolver{r} }

type serviceResolver struct{ *Resolver }
