package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	model1 "github.com/augustdev/autoclip/internal/graph/model"
)

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, name string) (*model1.CreateAPIKeyResult, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	result, err := r.AuthService.GenerateAPIKey(ctx, userID, name)
	if err != nil {
		return nil, fmt.Errorf("failed to create API key: %w", err)
	}

	return &model1.CreateAPIKeyResult{
		APIKey: &model1.APIKey{
			ID:        fmt.Sprintf("%d", result.ID),
			Name:      result.Name,
			Prefix:    result.Prefix,
			CreatedAt: result.CreatedAt,
		},
		Secret: result.FullKey,
	}, nil
}

// RevokeAPIKey is the resolver for the revokeAPIKey field.
func (r *mutationResolver) RevokeAPIKey(ctx context.Context, id string) (bool, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}

	var keyID int64
	if _, err := fmt.Sscanf(id, "%d", &keyID); err != nil {
		return false, fmt.Errorf("invalid key ID: %w", err)
	}

	if err := r.AuthService.RevokeAPIKey(ctx, userID, keyID); err != nil {
		return false, fmt.Errorf("failed to revoke API key: %w", err)
	}

	return true, nil
}

// UpdateFlyioCredentials is the resolver for the updateFlyioCredentials field.
func (r *mutationResolver) UpdateFlyioCredentials(ctx context.Context, token string, organization string) (bool, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}

	encryptedToken, err := r.AuthService.EncryptToken(token)
	if err != nil {
		return false, fmt.Errorf("failed to encrypt token: %w", err)
	}

	_, err = r.AuthService.UpdateFlyioCredentials(ctx, userID, encryptedToken, organization)
	if err != nil {
		return false, fmt.Errorf("failed to update credentials: %w", err)
	}

	return true, nil
}

// RemoveFlyioCredentials is the resolver for the removeFlyioCredentials field.
func (r *mutationResolver) RemoveFlyioCredentials(ctx context.Context) (bool, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return false, err
	}

	_, err = r.AuthService.UpdateFlyioCredentials(ctx, userID, "", "")
	if err != nil {
		return false, fmt.Errorf("failed to remove credentials: %w", err)
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model1.User, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.AuthService.GetUserByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}

	var avatarURL *string
	if user.AvatarUrl.Valid {
		avatarURL = &user.AvatarUrl.String
	}

	hasFlyioCredentials := user.FlyioToken.Valid && user.FlyioToken.String != ""

	return &model1.User{
		ID:                  fmt.Sprintf("%d", user.ID),
		GithubUsername:      user.GithubUsername,
		AvatarURL:           avatarURL,
		CreatedAt:           user.CreatedAt.Time,
		HasFlyioCredentials: hasFlyioCredentials,
	}, nil
}

// MyAPIKeys is the resolver for the myAPIKeys field.
func (r *queryResolver) MyAPIKeys(ctx context.Context) ([]*model1.APIKey, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	keys, err := r.AuthService.ListAPIKeys(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to list API keys: %w", err)
	}

	result := make([]*model1.APIKey, len(keys))
	for i, key := range keys {
		var lastUsedAt *time.Time
		if key.LastUsedAt.Valid {
			t := key.LastUsedAt.Time
			lastUsedAt = &t
		}

		result[i] = &model1.APIKey{
			ID:         fmt.Sprintf("%d", key.ID),
			Name:       key.Name,
			Prefix:     key.KeyPrefix,
			LastUsedAt: lastUsedAt,
			CreatedAt:  key.CreatedAt.Time,
		}
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
